name: gitlstreefs build

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest # Use a Debian-based runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Action to check out your repository code

    - name: Update apt
      run: |
        apt-get update # Update package lists
        apt-get install -yq \
        podman

    - name: build
      run: ./podman_build.sh
